name = "storybook"
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2024-01-31"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "service-worker"

[env.production]
name = "storybook-prod"
route = "example.com/*"
zone_id = ""

[observability]
enabled = true
